sudo: required
services:
  - docker
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
language: python
python: 2.7
env:
  - TOX_ENV=py36
  - TOX_ENV=py35
  - TOX_ENV=py34
  - TOX_ENV=py27
  - TOX_ENV=pep8
  - TOX_ENV=docs
  - TOX_ENV=py_func
  - TOX_ENV=cli_func
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
